// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	timescaledb: {
		enabled: true
		image: {
			repository: "timescale/timescaledb"
			tag:        "latest-pg15"
		}
		user:     "postgres"
		password: "postgres"
		database: "spirit_in_physics"
		storage:  "10Gi"
	}
	temporal: {
		enabled: true
		image: {
			repository: "temporalio/auto-setup"
			tag:        "latest"
		}
	}
	gateway: {
		enabled:  true
		hostname: "spirit-in-physics.gftd.ai"
	}
	lakefs: {
		enabled: true
		database: {
			connectionString: "postgresql://postgres:postgres@infra-timescaledb:5432/lakefs?sslmode=disable"
		}
		auth: {
			encryptSecretKey: "base64-encoded-secret-key-placeholder"
		}
		blockstore: {
			s3: {
				endpoint:        "http://infra-minio:9000"
				accessKeyId:     "minioadmin"
				secretAccessKey: "minioadmin"
			}
		}
	}
}
