// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	timescaledb: {
		enabled: true
		image: {
			repository: "timescale/timescaledb"
			tag:        "latest-pg15"
		}
		user:     "postgres"
		password: "postgres"
		database: "spirit_in_physics"
		storage:  "10Gi"
		storageClass: "standard"
	}
	temporal: {
		enabled: true
		image: {
			repository: "temporalio/auto-setup"
			tag:        "latest"
		}
	}
	gateway: {
		enabled:  true
		hostname: "spirit-in-physics.gftd.ai"
	}
	minio: {
		enabled: false
		storageClass: "standard"
	}
}
