apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Config Connector resources (require CRDs)
  # - gcs-bucket.yaml
  # - gcs-iam.yaml
  - cert-manager/certificate.yaml
  - cert-manager/researcher-certificate.yaml
  - cert-manager/clusterissuer.yaml
  - cert-manager/cleanup-rbac.yaml
  - cert-manager/cleanup-cronjob.yaml
  - gateway/infra-gateway.yaml
  - gateway/infra-https-redirect.yaml
  - gateway/infra-main-route.yaml
  - gateway/infra-researcher-route.yaml
