apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccounts/api.yaml
  - serviceaccounts/importer.yaml
  - serviceaccounts/portal.yaml
  - services/api.yaml
  - services/importer.yaml
  - services/infra-timescaledb.yaml
  - services/portal.yaml
  - services/researcher.yaml
  - deployments/api.yaml
  - deployments/importer.yaml
  - deployments/portal.yaml
  - deployments/researcher.yaml
  - statefulsets/infra-timescaledb.yaml
