apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cert-manager/certificate.yaml
  - cert-manager/clusterissuer.yaml
  - gateway/infra-gateway.yaml
  - gateway/infra-https-redirect.yaml
  - gateway/infra-main-route.yaml
  - serviceaccounts/grpc-service.yaml
  - serviceaccounts/import-service.yaml
  - serviceaccounts/import-worker.yaml
  - serviceaccounts/portal.yaml
  - serviceaccounts/temporal-ts.yaml
  - services/grpc-service.yaml
  - services/import-service.yaml
  - services/import-worker.yaml
  - services/infra-minio.yaml
  - services/infra-temporal.yaml
  - services/infra-timescaledb.yaml
  - services/portal.yaml
  - services/temporal-ts.yaml
  - deployments/grpc-service.yaml
  - deployments/import-service.yaml
  - deployments/import-worker.yaml
  - deployments/infra-temporal.yaml
  - deployments/portal.yaml
  - deployments/temporal-ts.yaml
  - statefulsets/infra-minio.yaml
  - statefulsets/infra-timescaledb.yaml
