apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cert-manager/certificate.yaml
  - cert-manager/clusterissuer.yaml
  - cert-manager/cleanup-rbac.yaml
  - cert-manager/cleanup-cronjob.yaml
  - gateway/infra-gateway.yaml
  - gateway/infra-https-redirect.yaml
  - gateway/infra-main-route.yaml
  - serviceaccounts/grpc-service.yaml
  - serviceaccounts/import-service.yaml
  - serviceaccounts/import-worker.yaml
  - serviceaccounts/portal.yaml
  - serviceaccounts/dapr-ts.yaml
  - services/grpc-service.yaml
  - services/import-service.yaml
  - services/import-worker.yaml
  - services/infra-timescaledb.yaml
  - services/portal.yaml
  - services/dapr-ts.yaml
  - gcs-bucket.yaml
  - gcs-iam.yaml
  # Dapr components
  - dapr/statestore.yaml
  - dapr/pubsub.yaml
  - dapr/workflow.yaml
  - deployments/dapr-redis.yaml
  - deployments/grpc-service.yaml
  - deployments/import-service.yaml
  - deployments/import-worker.yaml
  - deployments/portal.yaml
  - deployments/dapr-ts.yaml
  - statefulsets/infra-timescaledb.yaml
