'use client';

//! GraphQL React Hooks (Type-Safe)
//! 
//! Merkle DAG: graphql.hooks.participant
//! OWL: spirit:GraphQL Service Port React hooks

import * as Apollo from '@apollo/client';
import { GET_PARTICIPANTS, GET_PARTICIPANT } from './queries/participants';
import { GET_CONSENT } from './queries/consent';
import { GET_SESSIONS, GET_SESSIONS_BY_PARTICIPANT, GET_SESSION_EVENTS } from './queries/sessions';
import { GET_EMOTION_RESULTS, GET_EMOTION_STATISTICS } from './queries/emotions';
import { CREATE_PARTICIPANT, SAVE_CONSENT } from './mutations/participants';
import { SAVE_SESSION } from './mutations/sessions';
import { SAVE_VIDEO } from './mutations/artifacts';
import { ANALYZE_PARTICIPANT, ANALYZE_ALL_PARTICIPANTS } from './mutations/analysis';
import { ANALYZE_VIDEO_EMOTIONS } from './mutations/emotions';

// Types will be generated by GraphQL Code Generator
// For now, using any - will be replaced with generated types

// Query hooks
export function useParticipants(options?: Apollo.QueryHookOptions<any>) {
  return Apollo.useQuery<any>(GET_PARTICIPANTS, options);
}

export function useParticipant(
  id: string,
  options?: Apollo.QueryHookOptions<any, { id: string }>
) {
  return Apollo.useQuery<any, { id: string }>(GET_PARTICIPANT, {
    ...options,
    variables: { id },
    skip: !id,
  });
}

export function useConsent(
  participantId: string,
  options?: Apollo.QueryHookOptions<any, { participantId: string }>
) {
  return Apollo.useQuery<any, { participantId: string }>(GET_CONSENT, {
    ...options,
    variables: { participantId },
    skip: !participantId,
  });
}

export function useSessions(
  participantId?: string,
  options?: Apollo.QueryHookOptions<any, { participantId?: string }>
) {
  return Apollo.useQuery<any, { participantId?: string }>(GET_SESSIONS, {
    ...options,
    variables: { participantId: participantId || undefined },
  });
}

export function useSessionsByParticipant(
  participantId: string,
  options?: Apollo.QueryHookOptions<any, { participantId: string }>
) {
  return Apollo.useQuery<any, { participantId: string }>(GET_SESSIONS_BY_PARTICIPANT, {
    ...options,
    variables: { participantId },
    skip: !participantId,
  });
}

export function useSessionEvents(
  participantId: string,
  sessionId: string,
  options?: Apollo.QueryHookOptions<any, { participantId: string; sessionId: string }>
) {
  return Apollo.useQuery<any, { participantId: string; sessionId: string }>(GET_SESSION_EVENTS, {
    ...options,
    variables: { participantId, sessionId },
    skip: !participantId || !sessionId,
  });
}

export function useEmotionResults(
  participantId: string,
  options?: Apollo.QueryHookOptions<any, { participantId: string }>
) {
  return Apollo.useQuery<any, { participantId: string }>(GET_EMOTION_RESULTS, {
    ...options,
    variables: { participantId },
    skip: !participantId,
  });
}

export function useEmotionStatistics(options?: Apollo.QueryHookOptions<any>) {
  return Apollo.useQuery<any>(GET_EMOTION_STATISTICS, options);
}

// Mutation hooks
export function useCreateParticipant(
  options?: Apollo.MutationHookOptions<any, any>
) {
  return Apollo.useMutation<any, any>(CREATE_PARTICIPANT, options);
}

export function useSaveConsent(
  options?: Apollo.MutationHookOptions<any, any>
) {
  return Apollo.useMutation<any, any>(SAVE_CONSENT, options);
}

export function useSaveSession(
  options?: Apollo.MutationHookOptions<any, any>
) {
  return Apollo.useMutation<any, any>(SAVE_SESSION, options);
}

export function useSaveVideo(
  options?: Apollo.MutationHookOptions<any, any>
) {
  return Apollo.useMutation<any, any>(SAVE_VIDEO, options);
}

export function useAnalyzeParticipant(
  options?: Apollo.MutationHookOptions<any, any>
) {
  return Apollo.useMutation<any, any>(ANALYZE_PARTICIPANT, options);
}

export function useAnalyzeAllParticipants(
  options?: Apollo.MutationHookOptions<any, any>
) {
  return Apollo.useMutation<any, any>(ANALYZE_ALL_PARTICIPANTS, options);
}

export function useAnalyzeVideoEmotions(
  options?: Apollo.MutationHookOptions<any, any>
) {
  return Apollo.useMutation<any, any>(ANALYZE_VIDEO_EMOTIONS, options);
}

