# acm-config.yaml
configSync:
  enabled: true
  sourceFormat: unstructured
  oci:
    image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/manifests:latest
    auth: gcpserviceaccount
    gcpServiceAccountEmail: config-sync-sa@com-junkawasaki-sip.iam.gserviceaccount.com
policyController:
  enabled: false
hierarchyController:
  enabled: false
configConnector:
  enabled: true
