apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: spirit-in-physics

build:
  local:
    push: false
  artifacts:
    - image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/www
      context: ./apps/web
      docker:
        dockerfile: Dockerfile
    - image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/api
      context: ./performers/services/grpc
      docker:
        dockerfile: Dockerfile
    - image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/importer
      context: ./performers/services/import
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - manifests/overlays/local
    buildArgs:
      - --load-restrictor=LoadRestrictionsNone

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: www
    namespace: spirit-in-physics
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: api
    namespace: spirit-in-physics
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: importer
    namespace: spirit-in-physics
    port: 8082
    localPort: 8082
  - resourceType: service
    resourceName: infra-timescaledb
    namespace: spirit-in-physics
    port: 5432
    localPort: 5432
