version: '3'

tasks:
  apply-local:
    desc: Apply manifests to local cluster using Kustomize
    cmds:
      - kubectl kustomize manifests/overlays/local | kubectl apply -f -

  push-manifest:
    desc: Render and push manifests for GKE to Artifact Registry
    cmds:
      - mkdir -p .build/manifests
      - kubectl kustomize manifests/overlays/gke > .build/manifests/all.yaml
      - gcloud artifacts oci upload --source=.build/manifests --image=asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/manifests:latest

  nix-build-portal:
    desc: Build portal image with Docker and apply locally
    cmds:
      - docker build -t asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/svelte-app:latest ./apps/svelte-app
      - task: apply-local

