version: '3'

tasks:
  apply-local:
    desc: Apply manifests to local cluster using Kustomize
    cmds:
      - kubectl kustomize manifests/overlays/local | kubectl apply -f -

  push-manifest:
    desc: Render and push manifests for GKE to Artifact Registry
    cmds:
      - mkdir -p .build/manifests
      - kubectl kustomize manifests/overlays/gke > .build/manifests/all.yaml
      - |
        cat <<EOF > .build/manifests/Dockerfile
        FROM scratch
        COPY all.yaml /
        EOF
      - docker build -t asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/manifests:latest .build/manifests
      - docker push asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/manifests:latest

  push-app:
    desc: Build and push svelte-app image to Artifact Registry
    cmds:
      - docker build --platform linux/amd64 -t asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/svelte-app:latest apps/svelte-app
      - docker push asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/svelte-app:latest
      - kubectl rollout restart deployment portal -n spirit-in-physics

