apiVersion: v1
kind: Service
metadata:
  name: importer
  namespace: spirit-in-physics
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: importer
