apiVersion: v1
kind: Service
metadata:
  name: infra-temporal
  namespace: spirit-in-physics
spec:
  ports:
  - name: grpc
    port: 7233
    protocol: TCP
    targetPort: 7233
  - name: ui
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: temporal
