apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: infra
    app.kubernetes.io/version: 0.0.0-devel
  name: infra-temporal
  namespace: spirit-in-physics
spec:
  ports:
  - name: grpc
    port: 7233
    protocol: TCP
    targetPort: 7233
  - name: ui
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: temporal
    app.kubernetes.io/name: infra

