apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: infra
    app.kubernetes.io/version: 0.0.0-devel
  name: infra-timescaledb
  namespace: spirit-in-physics
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: timescaledb
    app.kubernetes.io/name: infra

