apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: temporal-ts
    app.kubernetes.io/version: 0.0.0-devel
  name: temporal-ts
  namespace: spirit-in-physics

apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: temporal-ts
    app.kubernetes.io/version: 0.0.0-devel
  name: temporal-ts
  namespace: spirit-in-physics
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: temporal-ts
  type: ClusterIP

