apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: infra
    app.kubernetes.io/version: 0.0.0-devel
  name: infra-timescaledb
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
      app.kubernetes.io/name: infra
  serviceName: infra-timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
        app.kubernetes.io/name: infra
    spec:
      containers:
      - args:
        - -c
        - max_connections=200
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: spirit_in_physics
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: timescale/timescaledb:latest-pg15
        name: timescaledb
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 70:70 /var/lib/postgresql/data
        image: busybox
        name: fix-permissions
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      securityContext:
        fsGroup: 70
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard

