apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra-timescaledb
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  serviceName: infra-timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - args:
        - -c
        - max_connections=200
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: spirit_in_physics
        image: timescale/timescaledb:latest-pg15
        name: timescaledb
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
