syntax = "proto3";

package import.v1;

option go_package = "github.com/spirit-in-physics/services/grpc/gen/proto/import/v1;importv1";

service ImportService {
  rpc ImportParticipants(ImportParticipantsRequest) returns (ImportParticipantsResponse);
  rpc ImportSessions(ImportSessionsRequest) returns (ImportSessionsResponse);
  rpc ImportEmotions(ImportEmotionsRequest) returns (ImportEmotionsResponse);
  rpc ImportTimeline(ImportTimelineRequest) returns (ImportTimelineResponse);
}

message ImportParticipantsRequest {}
message ImportParticipantsResponse {
  bool success = 1;
  int32 total = 2;
  int32 processed = 3;
}

message ImportSessionsRequest {}
message ImportSessionsResponse {
  bool success = 1;
  int32 total = 2;
  int32 processed = 3;
}

message ImportEmotionsRequest {}
message ImportEmotionsResponse {
  bool success = 1;
  int32 total = 2;
  int32 processed = 3;
}

message ImportTimelineRequest {}
message ImportTimelineResponse {
  bool success = 1;
  int32 total = 2;
  int32 processed = 3;
}
