// Merkle DAG: graphql.service.schema
// GraphQL schema definition using juniper-from-schema

use juniper::{RootNode, EmptyMutation, EmptySubscription};
use sqlx::Pool;
use sqlx::Postgres;
use crate::resolvers::{ParticipantQuery, TimelineQuery, ParticipantMutation};
use crate::auth::context::AuthContext;
use serde_json;

// Generate schema from GraphQL SDL file
// This macro generates types and traits directly in the current module scope
// The path is relative to the crate root (performers/services/graphql/)
juniper_from_schema::graphql_schema_from_file!(
    "schema.graphql"
);

// JSON scalar type implementation
// juniper-from-schema generates JSON as: pub struct JSON(pub String);
// We need to implement GraphQLType, FromInputValue, and conversion to/from serde_json::Value

// Conversion between JSON (String wrapper) and serde_json::Value
impl From<serde_json::Value> for JSON {
    fn from(value: serde_json::Value) -> Self {
        JSON(serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()))
    }
}

impl From<JSON> for serde_json::Value {
    fn from(json: JSON) -> Self {
        serde_json::from_str(&json.0).unwrap_or_else(|_| serde_json::Value::Null)
    }
}

impl<'a> From<&'a JSON> for serde_json::Value {
    fn from(json: &'a JSON) -> Self {
        serde_json::from_str(&json.0).unwrap_or_else(|_| serde_json::Value::Null)
    }
}

// Note: juniper-from-schema generates JSON scalar type implementation automatically
// JSON is generated as: pub struct JSON(pub String);
// The generated implementation handles GraphQLType, FromInputValue, etc.
// We only need to provide conversion helpers to/from serde_json::Value

// Alias for JSON scalar type (generated as JSON, but we use Json in resolvers)
pub use JSON as Json;

// Context type for Juniper
pub struct Context {
    pub pool: Pool<Postgres>,
    pub auth: Option<AuthContext>,
}

impl juniper::Context for Context {}

// Schema type - juniper-from-schema generates a Schema type
// We use the generated Schema type instead of defining our own
// Note: The generated Schema type is based on RootNode<Query, Mutation, EmptySubscription>

pub struct Query;

// Implement QueryFields trait generated by juniper-from-schema
impl QueryFields for Query {
    fn field_participants(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        _trail: &QueryTrail<'_, Participant, Walked>,
    ) -> juniper::FieldResult<Vec<Participant>> {
        let context = executor.context();
        // Note: async resolvers need to be handled differently
        // For now, we'll use blocking approach with tokio runtime
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::participants(context)
        )
    }

    fn field_participant(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        id: juniper::ID,
        _trail: &QueryTrail<'_, Participant, Walked>,
    ) -> juniper::FieldResult<Option<Participant>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::participant(context, id)
        )
    }

    fn field_stimulus_words(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        _trail: &QueryTrail<'_, StimulusWord, Walked>,
    ) -> juniper::FieldResult<Vec<StimulusWord>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::stimulus_words(context)
        )
    }

    fn field_stimulus_word(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        id: i32,
        _trail: &QueryTrail<'_, StimulusWord, Walked>,
    ) -> juniper::FieldResult<Option<StimulusWord>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::stimulus_word(context, id)
        )
    }

    fn field_sessions(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        participant_id: juniper::ID,
        _trail: &QueryTrail<'_, Session, Walked>,
    ) -> juniper::FieldResult<Vec<Session>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::sessions(context, participant_id)
        )
    }

    fn field_timeline(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        start_time: Option<String>,
        end_time: Option<String>,
        interval: Option<String>,
        _trail: &QueryTrail<'_, TimelinePoint, Walked>,
    ) -> juniper::FieldResult<Vec<TimelinePoint>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::timeline(context, participant_id, session_id, start_time, end_time, interval)
        )
    }

    fn field_word_aggregates(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        _trail: &QueryTrail<'_, WordAggregate, Walked>,
    ) -> juniper::FieldResult<Vec<WordAggregate>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::word_aggregates(context, participant_id, session_id)
        )
    }

    fn field_emotion_vectors(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        _trail: &QueryTrail<'_, EmotionVector, Walked>,
    ) -> juniper::FieldResult<Vec<EmotionVector>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::emotion_vectors(context, participant_id, session_id)
        )
    }

    fn field_word_statistics(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        _trail: &QueryTrail<'_, WordStatistics, Walked>,
    ) -> juniper::FieldResult<Vec<WordStatistics>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::word_statistics(context, participant_id, session_id)
        )
    }
}

pub struct Mutation;

// Implement MutationFields trait generated by juniper-from-schema
impl MutationFields for Mutation {
    fn field_create_participant(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        input: CreateParticipantInput,
        _trail: &QueryTrail<'_, Participant, Walked>,
    ) -> juniper::FieldResult<Participant> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantMutation::create_participant(context, input)
        )
    }

    fn field_create_session(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        input: CreateSessionInput,
        _trail: &QueryTrail<'_, Session, Walked>,
    ) -> juniper::FieldResult<Session> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantMutation::create_session(context, input)
        )
    }

    fn field_upload_artifact(
        &self,
        executor: &juniper::Executor<'_, '_, Context>,
        input: UploadArtifactInput,
    ) -> juniper::FieldResult<String> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantMutation::upload_artifact(context, input)
        )
    }
}

pub fn create_schema(_pool: Pool<Postgres>) -> Schema {
    Schema::new(Query, Mutation, EmptySubscription::default())
}

// Note: juniper-from-schema generates types directly in this module's scope as `pub`
// These types are accessible from other modules via `crate::schema::TypeName`
// The generated types include:
// - Participant, StimulusWord, Session, TimelinePoint, WordAggregate, etc.
// - CreateParticipantInput, CreateSessionInput, UploadArtifactInput
// - QueryFields, MutationFields, QueryTrail, Walked traits
//
// Since the module is declared as `pub mod schema` in lib.rs,
// and juniper-from-schema generates types as `pub`, they should be accessible directly.
// If they're not accessible, it may be because the macro hasn't generated them yet or there's a compilation error.

// Note: juniper-from-schema generates a Schema type, so we don't need to re-export GraphQLSchema as Schema
// The generated Schema type should be used instead
