// Merkle DAG: graphql.service.schema
// GraphQL schema definition using juniper-from-schema

use juniper::{RootNode, EmptyMutation};
use sqlx::Pool;
use sqlx::Postgres;
use crate::resolvers::{ParticipantQuery, TimelineQuery, ParticipantMutation};
use crate::auth::context::AuthContext;
use serde_json;

// Generate schema from GraphQL SDL file
// This macro generates types and traits based on the schema
// The path is relative to the crate root (performers/services/graphql/)
juniper_from_schema::graphql_schema_from_file!(
    "schema.graphql"
);

// JSON scalar type implementation
// juniper-from-schema generates JSON as: pub struct JSON(pub String);
// We need to implement GraphQLType, FromInputValue, and conversion to/from serde_json::Value

// Conversion between JSON (String wrapper) and serde_json::Value
impl From<serde_json::Value> for JSON {
    fn from(value: serde_json::Value) -> Self {
        JSON(serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()))
    }
}

impl From<JSON> for serde_json::Value {
    fn from(json: JSON) -> Self {
        serde_json::from_str(&json.0).unwrap_or_else(|_| serde_json::Value::Null)
    }
}

impl<'a> From<&'a JSON> for serde_json::Value {
    fn from(json: &'a JSON) -> Self {
        serde_json::from_str(&json.0).unwrap_or_else(|_| serde_json::Value::Null)
    }
}

// Note: juniper-from-schema generates JSON scalar type implementation automatically
// JSON is generated as: pub struct JSON(pub String);
// The generated implementation handles GraphQLType, FromInputValue, etc.
// We only need to provide conversion helpers to/from serde_json::Value

// Alias for JSON scalar type (generated as JSON, but we use Json in resolvers)
pub use JSON as Json;

// Context type for Juniper
pub struct Context {
    pub pool: Pool<Postgres>,
    pub auth: Option<AuthContext>,
}

impl juniper::Context for Context {}

// Schema type - juniper 0.14 RootNode takes Query, Mutation, and ScalarValue
// Note: juniper 0.14 doesn't support subscriptions, so we use DefaultScalarValue
pub type GraphQLSchema = RootNode<'static, Query, Mutation>;

pub struct Query;

// Implement QueryFields trait generated by juniper-from-schema
impl QueryFields for Query {
    fn field_participants(
        &self,
        executor: &juniper::Executor<'_, Context>,
        _trail: &QueryTrail<'_, Participant, Walked>,
    ) -> juniper::FieldResult<Vec<Participant>> {
        let context = executor.context();
        // Note: async resolvers need to be handled differently
        // For now, we'll use blocking approach with tokio runtime
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::participants(context)
        )
    }

    fn field_participant(
        &self,
        executor: &juniper::Executor<'_, Context>,
        id: juniper::ID,
        _trail: &QueryTrail<'_, Participant, Walked>,
    ) -> juniper::FieldResult<Option<Participant>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::participant(context, id)
        )
    }

    fn field_stimulus_words(
        &self,
        executor: &juniper::Executor<'_, Context>,
        _trail: &QueryTrail<'_, StimulusWord, Walked>,
    ) -> juniper::FieldResult<Vec<StimulusWord>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::stimulus_words(context)
        )
    }

    fn field_stimulus_word(
        &self,
        executor: &juniper::Executor<'_, Context>,
        id: i32,
        _trail: &QueryTrail<'_, StimulusWord, Walked>,
    ) -> juniper::FieldResult<Option<StimulusWord>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantQuery::stimulus_word(context, id)
        )
    }

    fn field_sessions(
        &self,
        executor: &juniper::Executor<'_, Context>,
        participant_id: juniper::ID,
        _trail: &QueryTrail<'_, Session, Walked>,
    ) -> juniper::FieldResult<Vec<Session>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::sessions(context, participant_id)
        )
    }

    fn field_timeline(
        &self,
        executor: &juniper::Executor<'_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        start_time: Option<String>,
        end_time: Option<String>,
        interval: Option<String>,
        _trail: &QueryTrail<'_, TimelinePoint, Walked>,
    ) -> juniper::FieldResult<Vec<TimelinePoint>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::timeline(context, participant_id, session_id, start_time, end_time, interval)
        )
    }

    fn field_word_aggregates(
        &self,
        executor: &juniper::Executor<'_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        _trail: &QueryTrail<'_, WordAggregate, Walked>,
    ) -> juniper::FieldResult<Vec<WordAggregate>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::word_aggregates(context, participant_id, session_id)
        )
    }

    fn field_emotion_vectors(
        &self,
        executor: &juniper::Executor<'_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        _trail: &QueryTrail<'_, EmotionVector, Walked>,
    ) -> juniper::FieldResult<Vec<EmotionVector>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::emotion_vectors(context, participant_id, session_id)
        )
    }

    fn field_word_statistics(
        &self,
        executor: &juniper::Executor<'_, Context>,
        participant_id: juniper::ID,
        session_id: Option<juniper::ID>,
        _trail: &QueryTrail<'_, WordStatistics, Walked>,
    ) -> juniper::FieldResult<Vec<WordStatistics>> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            TimelineQuery::word_statistics(context, participant_id, session_id)
        )
    }
}

pub struct Mutation;

// Implement MutationFields trait generated by juniper-from-schema
impl MutationFields for Mutation {
    fn field_create_participant(
        &self,
        executor: &juniper::Executor<'_, Context>,
        input: CreateParticipantInput,
        _trail: &QueryTrail<'_, Participant, Walked>,
    ) -> juniper::FieldResult<Participant> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantMutation::create_participant(context, input)
        )
    }

    fn field_create_session(
        &self,
        executor: &juniper::Executor<'_, Context>,
        input: CreateSessionInput,
        _trail: &QueryTrail<'_, Session, Walked>,
    ) -> juniper::FieldResult<Session> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantMutation::create_session(context, input)
        )
    }

    fn field_upload_artifact(
        &self,
        executor: &juniper::Executor<'_, Context>,
        input: UploadArtifactInput,
    ) -> juniper::FieldResult<String> {
        let context = executor.context();
        tokio::runtime::Handle::current().block_on(
            ParticipantMutation::upload_artifact(context, input)
        )
    }
}

pub fn create_schema(_pool: Pool<Postgres>) -> GraphQLSchema {
    GraphQLSchema::new(Query, Mutation)
}

// Export GraphQLSchema as Schema for external use
// Note: juniper-from-schema may generate a Schema type, so we use GraphQLSchema to avoid conflicts
pub use GraphQLSchema as Schema;

// Re-export types generated by juniper-from-schema for use in resolvers
// These types are generated by the macro above and are available in the current scope
// We need to re-export them so they can be used in other modules
// Note: If there are conflicts, it means juniper-from-schema already exports them
pub use {
    Participant, StimulusWord, Session, TimelinePoint, WordAggregate,
    EmotionVector, WordStatistics, EmotionData, PhysiologicalData,
    CreateParticipantInput, CreateSessionInput, UploadArtifactInput,
};
