apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: portal
    app.kubernetes.io/version: 0.0.0-devel
  name: portal
  namespace: spirit-in-physics

