// GraphQL queries for researcher dashboard
// These will be generated by Houdini, but we define them here for reference

export const PARTICIPANTS_QUERY = `
	query GetParticipants {
		participants {
			id
			age
			gender
			handedness
			createdAt
			updatedAt
		}
	}
`;

export const PARTICIPANT_QUERY = `
	query GetParticipant($id: ID!) {
		participant(id: $id) {
			id
			age
			gender
			handedness
			createdAt
			updatedAt
		}
	}
`;

export const SESSIONS_QUERY = `
	query GetSessions($participantId: ID!) {
		sessions(participantId: $participantId) {
			id
			participantId
			sessionIndex
			startTs
			endTs
			events
			createdAt
			updatedAt
		}
	}
`;

export const TIMELINE_QUERY = `
	query GetTimeline($participantId: ID!, $sessionId: ID, $startTime: String, $endTime: String, $interval: String) {
		timeline(participantId: $participantId, sessionId: $sessionId, startTime: $startTime, endTime: $endTime, interval: $interval) {
			time
			participantId
			sessionId
			word
			eventType
			reactionValue
			reactionTime
			hasResponse
			emotions {
				name
				score
				fileType
				color
			}
			physiological {
				timestamp
				value
				metadata
			}
			metadata
		}
	}
`;

export const WORD_AGGREGATES_QUERY = `
	query GetWordAggregates($participantId: ID!, $sessionId: ID!) {
		wordAggregates(participantId: $participantId, sessionId: $sessionId) {
			participantId
			sessionId
			word
			count
			avgReactionValue
			sumReactionValue
			avgReactionTime
			sumReactionTime
			avgPhysiological
			sumPhysAbs
			physSeries
			rtSeries
			rvSeries
			firstTime
			lastTime
		}
	}
`;

export const EMOTION_VECTORS_QUERY = `
	query GetEmotionVectors($participantId: ID!, $sessionId: ID!) {
		emotionVectors(participantId: $participantId, sessionId: $sessionId) {
			participantId
			sessionId
			word
			joySum
			sadnessSum
			angerSum
			fearSum
			surpriseSum
			disgustSum
			calmSum
			focusSum
			excitementSum
			confusionSum
			emotionEntryCount
			emotionByModality
		}
	}
`;
