import { get } from 'svelte/store';
import { kawasakiStore } from '../store';
import type { Word } from '../types';
import { client } from '$lib/graphql/client';

// GraphQL query will be generated by Houdini
// For now, use a simple fetch approach
export async function useStimulusWords(): Promise<{ loading: boolean; error: Error | null; words: Word[] }> {
	const store = get(kawasakiStore);
	
	if (store.stimulusWords.length > 0) {
		return { loading: false, error: null, words: store.stimulusWords };
	}

	try {
		// Use Houdini client to fetch stimulus words
		// This will be replaced with generated Houdini queries
		const response = await fetch('/api/graphql', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({
				query: `
					query GetStimulusWords {
						stimulusWords {
							id
							japanese
							english
							pronunciation
						}
					}
				`
			})
		});

		const result = await response.json();
		
		if (result.data?.stimulusWords) {
			const words: Word[] = result.data.stimulusWords.map((sw: any) => ({
				word: sw.japanese,
				key: sw.id.toString()
			}));
			
			kawasakiStore.setStimulusWords(words);
			return { loading: false, error: null, words };
		}
		
		return { loading: false, error: null, words: [] };
	} catch (error) {
		console.error('Error fetching stimulus words:', error);
		return { loading: false, error: error as Error, words: [] };
	}
}
