apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Core resources that work in any Kubernetes environment
resources:
  - ../namespace.yaml
  - ../serviceaccounts/grpc-service.yaml
  - ../serviceaccounts/import-service.yaml
  - ../serviceaccounts/import-worker.yaml
  - ../serviceaccounts/portal.yaml
  - ../serviceaccounts/temporal-ts.yaml
  - ../services/grpc-service.yaml
  - ../services/import-service.yaml
  - ../services/import-worker.yaml
  - ../services/infra-temporal.yaml
  - ../services/infra-timescaledb.yaml
  - ../services/portal.yaml
  - ../services/temporal-ts.yaml
  - ../deployments/grpc-service.yaml
  - ../deployments/import-service.yaml
  - ../deployments/import-worker.yaml
  - ../deployments/infra-temporal.yaml
  - ../deployments/portal.yaml
  - ../deployments/temporal-ts.yaml
  - ../statefulsets/infra-timescaledb.yaml
