//! Data Import Activity
//! 
//! Merkle DAG: activities_rust.activities.data_import
//! OWL: spirit:DataImportProcess
//! JSON-LD: https://spirit-in-physics.gftd.ai/activity/DataImport

use crate::models::{Activity, ActivityContext, ActivityData, ActivityExecutionResult};
use crate::error::{ActivityError, ActivityResult};
use async_trait::async_trait;
use chrono::Utc;
use serde_json::{json, Value};
use std::path::{Path, PathBuf};
use std::fs;
use tokio::fs as tokio_fs;
use anyhow::Result as AnyhowResult;

/// Data Import Activity
/// 
/// Imports participant data from local filesystem to Supabase database
pub struct DataImportActivity {
    supabase_url: String,
    supabase_service_role_key: String,
}

impl DataImportActivity {
    pub fn new() -> Self {
        let supabase_url = std::env::var("SUPABASE_URL")
            .or_else(|_| std::env::var("NEXT_PUBLIC_SUPABASE_URL"))
            .unwrap_or_else(|_| "http://localhost:54321".to_string());
        
        let supabase_service_role_key = std::env::var("SUPABASE_SERVICE_ROLE_KEY")
            .unwrap_or_else(|_| "".to_string());

        Self {
            supabase_url,
            supabase_service_role_key,
        }
    }

    /// Resolve dataset root path (Docker and local environment)
    fn resolve_data_root_path(&self) -> PathBuf {
        // Check Docker path first
        if Path::new("/app/public/dataset").exists() {
            return PathBuf::from("/app/public/dataset");
        }
        
        // Local environment: try multiple paths
        let current_dir = std::env::current_dir().unwrap();
        let possible_paths = vec![
            current_dir.join("performers/systems/ResearcherApplication/src/public/dataset"),
            current_dir.join("public/dataset"),
            PathBuf::from("./public/dataset"),
        ];

        for path in possible_paths {
            if path.exists() {
                return path;
            }
        }

        // Default fallback
        current_dir.join("performers/systems/ResearcherApplication/src/public/dataset")
    }

    /// Get Supabase request headers
    fn supabase_request_headers(&self) -> reqwest::header::HeaderMap {
        let mut headers = reqwest::header::HeaderMap::new();
        headers.insert(
            "apikey",
            self.supabase_service_role_key.parse().unwrap(),
        );
        headers.insert(
            "Authorization",
            format!("Bearer {}", self.supabase_service_role_key).parse().unwrap(),
        );
        headers.insert(
            "Content-Type",
            "application/json".parse().unwrap(),
        );
        headers.insert(
            "Prefer",
            "return=representation".parse().unwrap(),
        );
        headers
    }

    /// Make HTTP request to Supabase REST API
    async fn supabase_request(
        &self,
        method: &str,
        path: &str,
        body: Option<&Value>,
    ) -> AnyhowResult<Value> {
        let url = format!("{}/rest/v1/{}", self.supabase_url, path);
        let client = reqwest::Client::new();

        let mut request = match method {
            "GET" => client.get(&url),
            "POST" => client.post(&url),
            "PATCH" => client.patch(&url),
            "PUT" => client.put(&url),
            "DELETE" => client.delete(&url),
            _ => return Err(anyhow::anyhow!("Unsupported HTTP method: {}", method)),
        };

        request = request.headers(self.supabase_request_headers());

        if let Some(body_data) = body {
            request = request.json(body_data);
        }

        let response = request.send().await?;

        let status = response.status();
        if !status.is_success() {
            let error_text = response.text().await.unwrap_or_default();
            return Err(anyhow::anyhow!("Supabase API error: {} - {}", status, error_text));
        }

        let data: Value = response.json().await?;
        Ok(data)
    }

    /// Ensure word exists in word_stimuli table (upsert by word text)
    async fn ensure_word_stimulus(&self, word: &str) -> AnyhowResult<i32> {
        // Check if word exists
        let path = format!("word_stimuli?word=eq.{}&select=id", urlencoding::encode(word));
        let existing: Vec<Value> = match self.supabase_request("GET", &path, None).await {
            Ok(Value::Array(arr)) => arr,
            Ok(_) => vec![],
            Err(_) => vec![],
        };

        if let Some(first) = existing.first() {
            if let Some(id) = first.get("id").and_then(|v| v.as_i64()) {
                return Ok(id as i32);
            }
        }

        // Insert new word (ID will be auto-generated by database)
        let word_data = json!({
            "word": word,
        });

        let result = self.supabase_request("POST", "word_stimuli", Some(&word_data)).await?;
        
        // Extract ID from response (array or single object)
        let id = match result {
            Value::Array(arr) => arr.first()
                .and_then(|v| v.get("id"))
                .and_then(|v| v.as_i64()),
            Value::Object(obj) => obj.get("id").and_then(|v| v.as_i64()),
            _ => None,
        };

        id.map(|id| id as i32)
            .ok_or_else(|| anyhow::anyhow!("Failed to get word_stimulus_id after insert"))
    }

    /// Import consent data
    async fn import_consent_data(
        &self,
        participant_id: &str,
        consent_path: &Path,
    ) -> AnyhowResult<()> {
        if !consent_path.exists() {
            // Create participant record even without consent.json
            let participant_data = json!({
                "id": participant_id,
            });
            self.supabase_request("POST", &format!("participants?on_conflict=id"), Some(&json!([participant_data]))).await?;
            return Ok(());
        }

        let content = tokio_fs::read_to_string(consent_path).await?;
        let consent: Value = serde_json::from_str(&content)?;

        // Upsert participant (use upsert pattern with Prefer header)
        let participant_data = json!({
            "id": participant_id,
            "name": consent.get("signature").and_then(|v| v.as_str()),
        });
        
        let mut headers = self.supabase_request_headers();
        headers.insert("Prefer", "resolution=merge-duplicates".parse().unwrap());
        
        let url = format!("{}/rest/v1/participants", self.supabase_url);
        let client = reqwest::Client::new();
        let response = client.post(&url)
            .headers(headers.clone())
            .json(&json!([participant_data]))
            .send().await?;

        let status = response.status();
        if !status.is_success() {
            let error_text = response.text().await.unwrap_or_default();
            return Err(anyhow::anyhow!("Failed to upsert participant: {} - {}", status, error_text));
        }

        // Upsert consent
        if consent.get("signature").is_some() || consent.get("agreedAt").is_some() {
            let consent_data = json!({
                "participant_id": participant_id,
                "signature": consent.get("signature").and_then(|v| v.as_str()).unwrap_or(""),
                "agreements": consent.get("agreements").cloned().unwrap_or(json!({})),
                "agreed_at": consent.get("agreedAt")
                    .and_then(|v| v.as_str())
                    .unwrap_or(&Utc::now().to_rfc3339()),
            });
            
            let consent_url = format!("{}/rest/v1/participant_consents", self.supabase_url);
            let consent_response = client.post(&consent_url)
                .headers(headers.clone())
                .json(&json!([consent_data]))
                .send().await?;

            let consent_status = consent_response.status();
            if !consent_status.is_success() {
                let error_text = consent_response.text().await.unwrap_or_default();
                return Err(anyhow::anyhow!("Failed to upsert consent: {} - {}", consent_status, error_text));
            }
        }

        Ok(())
    }

    /// Import session data
    async fn import_session_data(
        &self,
        participant_id: &str,
        session_path: &Path,
    ) -> AnyhowResult<(String, usize)> {
        if !session_path.exists() {
            return Ok((String::new(), 0));
        }

        let content = tokio_fs::read_to_string(session_path).await?;
        let session: Value = serde_json::from_str(&content)?;

        let events = session.get("events").and_then(|v| v.as_array()).cloned().unwrap_or_default();
        
        // Find session start/end events
        let session_started = events.iter().find(|e| {
            e.get("type").or_else(|| e.get("event_type"))
                .and_then(|v| v.as_str())
                .map(|s| s == "session_started")
                .unwrap_or(false)
        });
        let session_ended = events.iter()
            .rev()
            .find(|e| {
                e.get("type").or_else(|| e.get("event_type"))
                    .and_then(|v| v.as_str())
                    .map(|s| s == "response_window_closed")
                    .unwrap_or(false)
            });

        let start_time = session_started
            .and_then(|e| e.get("timestamp").and_then(|v| v.as_i64()))
            .map(|ts| chrono::DateTime::from_timestamp_millis(ts).unwrap_or_else(|| Utc::now()))
            .unwrap_or_else(|| Utc::now())
            .to_rfc3339();

        let end_time = session_ended
            .and_then(|e| e.get("timestamp").and_then(|v| v.as_i64()))
            .map(|ts| chrono::DateTime::from_timestamp_millis(ts).unwrap_or_else(|| Utc::now()).to_rfc3339());

        let session_type = "session-1"; // Determine based on events if needed

        // Upsert session (database will generate UUID for session_id if not provided)
        // We don't provide session_id, let database generate it
        let session_data = json!({
            "participant_id": participant_id,
            "session_type": session_type,
            "start_time": start_time,
            "end_time": end_time,
        });

        // Use upsert with conflict on participant_id + session_type
        let session_result = self.supabase_request(
            "POST",
            &format!("participant_experiment_sessions?on_conflict=participant_id,session_type"),
            Some(&json!([session_data])),
        ).await?;

        // Extract session UUID (database-generated)
        let session_uuid = match &session_result {
            Value::Array(arr) => arr.first()
                .and_then(|v| v.get("id"))
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            Value::Object(obj) => obj.get("id")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            _ => None,
        }.ok_or_else(|| anyhow::anyhow!("Failed to get session UUID after insert"))?;

        // Import word_displayed events as response data
        let word_displayed_events: Vec<_> = events.iter()
            .filter(|e| {
                e.get("type").or_else(|| e.get("event_type"))
                    .and_then(|v| v.as_str())
                    .map(|s| s == "word_displayed")
                    .unwrap_or(false)
            })
            .collect();

        let mut response_count = 0;
        for (_index, event) in word_displayed_events.iter().enumerate() {
            let word = event.get("payload")
                .and_then(|p| p.get("word"))
                .or_else(|| event.get("word"))
                .and_then(|v| v.as_str())
                .unwrap_or("unknown");

            // Ensure word exists in word_stimuli and get ID
            let word_stimulus_id = self.ensure_word_stimulus(word).await?;

            let timestamp = event.get("timestamp")
                .and_then(|v| v.as_i64())
                .map(|ts| chrono::DateTime::from_timestamp_millis(ts).unwrap_or_else(|| Utc::now()))
                .unwrap_or_else(|| Utc::now())
                .to_rfc3339();

            let response_data = json!({
                "participant_id": participant_id,
                "experiment_id": session_uuid,
                "word_stimulus_id": word_stimulus_id,
                "stimulus_word": word,
                "response_word": word, // Simplified: use same word
                "reaction_time_ms": 0,
                "session": session_type,
                "timestamp": timestamp,
            });

            self.supabase_request("POST", "participant_response_data", Some(&json!([response_data]))).await?;
            response_count += 1;
        }

        Ok((session_uuid, response_count))
    }

    /// Import emotion data from Hume AI CSV files
    async fn import_emotion_data(
        &self,
        participant_id: &str,
        base_path: &Path,
        session_uuid: &str,
    ) -> AnyhowResult<usize> {
        let entries = fs::read_dir(base_path)?;
        
        // Find HumeAI artifacts directory
        let hume_dir = entries
            .filter_map(|entry| entry.ok())
            .find(|entry| {
                entry.file_name().to_string_lossy().starts_with("HumeAI_artifacts_")
            });

        let hume_path = match hume_dir {
            Some(dir) => dir.path(),
            None => return Ok(0),
        };

        // Read CSV files recursively
        let mut record_count = 0;
        self.process_hume_csv_files(&hume_path, participant_id, session_uuid, &mut record_count).await?;

        Ok(record_count)
    }

    /// Process Hume AI CSV files recursively
    fn process_hume_csv_files_sync(
        &self,
        dir: &Path,
    ) -> AnyhowResult<Vec<PathBuf>> {
        let mut csv_files = Vec::new();
        let entries = fs::read_dir(dir)?;

        for entry in entries {
            let entry = entry?;
            let path = entry.path();

            if path.is_dir() {
                csv_files.extend(self.process_hume_csv_files_sync(&path)?);
            } else if path.extension().and_then(|s| s.to_str()) == Some("csv") {
                csv_files.push(path);
            }
        }

        Ok(csv_files)
    }

    /// Process Hume AI CSV files (async wrapper)
    async fn process_hume_csv_files(
        &self,
        dir: &Path,
        participant_id: &str,
        session_uuid: &str,
        record_count: &mut usize,
    ) -> AnyhowResult<()> {
        let csv_files = self.process_hume_csv_files_sync(dir)?;

        for csv_path in csv_files {
            let content = tokio_fs::read_to_string(&csv_path).await?;
            let lines: Vec<_> = content.lines().filter(|l| !l.trim().is_empty()).collect();

            if lines.len() < 2 {
                continue;
            }

            let header: Vec<_> = lines[0].split(',').map(|s| s.trim()).collect();
            
            // Create Hume analysis job first (database will generate ID)
            let job_data = json!({
                "participant_experiment_session_id": session_uuid,
                "status": "completed",
                "source_media_path": csv_path.file_name().and_then(|n| n.to_str()).unwrap_or(""),
            });

            let job_result = self.supabase_request("POST", "participant_hume_analysis_jobs", Some(&json!([job_data]))).await?;
            let job_id = match &job_result {
                Value::Array(arr) => arr.first()
                    .and_then(|v| v.get("id"))
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                Value::Object(obj) => obj.get("id")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string()),
                _ => None,
            }.ok_or_else(|| anyhow::anyhow!("Failed to get job ID"))?;
        
            // Determine emotion type from filename
            let file_name = csv_path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            let emotion_type = if file_name.contains("burst") {
                "burst"
            } else if file_name.contains("language") {
                "language"
            } else if file_name.contains("prosody") {
                "prosody"
            } else {
                "unknown"
            };

            // Parse CSV records
            for line in lines.iter().skip(1) {
                let values: Vec<_> = line.split(',').map(|s| s.trim()).collect();
                if values.len() != header.len() {
                    continue;
                }

                // Find BeginTime and EndTime column indices
                let begin_time_idx = header.iter().position(|h| *h == "BeginTime");
                let end_time_idx = header.iter().position(|h| *h == "EndTime");

                let begin_time = begin_time_idx
                    .and_then(|idx| values.get(idx))
                    .and_then(|v| v.parse::<f64>().ok())
                    .unwrap_or(0.0);

                let end_time = end_time_idx
                    .and_then(|idx| values.get(idx))
                    .and_then(|v| v.parse::<f64>().ok())
                    .unwrap_or(0.0);

                // Extract emotion values
                let mut emotions = json!({});
                for (i, col) in header.iter().enumerate() {
                    if *col != "Id" && *col != "BeginTime" && *col != "EndTime" {
                        if let Ok(num) = values[i].parse::<f64>() {
                            emotions[*col] = json!(num);
                        }
                    }
                }

                let prediction_data = json!({
                    "job_id": job_id,
                    "begin_time": begin_time,
                    "end_time": end_time,
                    "emotions": emotions,
                });

                let table_name = match emotion_type {
                    "burst" => "participant_hume_burst_predictions",
                    "language" => "participant_hume_language_predictions",
                    "prosody" => "participant_hume_prosody_predictions",
                    _ => continue,
                };

                self.supabase_request("POST", table_name, Some(&json!([prediction_data]))).await?;
                *record_count += 1;
            }
        }

        Ok(())
    }
}

#[async_trait]
impl Activity for DataImportActivity {
    fn id(&self) -> &str {
        "https://spirit-in-physics.gftd.ai/activity/DataImport"
    }

    fn name(&self) -> &str {
        "Data Import"
    }

    fn description(&self) -> &str {
        "Activity for importing participant data from local filesystem to Supabase database"
    }

    async fn execute(&self, context: &mut ActivityContext) -> ActivityResult<ActivityExecutionResult> {
        let start_time = std::time::Instant::now();

        // Get input: dataset path and participant ID
        let dataset_path_input = context.inputs.iter()
            .find(|input| input.r#type == "https://spirit-in-physics.gftd.ai/ontology#DatasetPath");
        
        let participant_id_input = context.inputs.iter()
            .find(|input| input.r#type == "https://spirit-in-physics.gftd.ai/ontology#ParticipantId");

        let participant_id = participant_id_input
            .and_then(|input| input.data.as_str().map(|s| s.to_string()))
            .ok_or_else(|| ActivityError::InvalidInput("Participant ID is required".to_string()))?;

        let data_root = dataset_path_input
            .and_then(|input| input.data.as_str().map(|s| PathBuf::from(s)))
            .unwrap_or_else(|| self.resolve_data_root_path());

        let base_path = data_root.join("participants").join(&participant_id);

        if !base_path.exists() {
            return Err(ActivityError::ConditionNotMet(
                format!("Participant directory not found: {}", base_path.display())
            ));
        }

        // Import consent data
        let consent_path = base_path.join("consent.json");
        self.import_consent_data(&participant_id, &consent_path)
            .await
            .map_err(|e| ActivityError::ExecutionFailed(format!("Failed to import consent: {}", e)))?;

        // Import session data
        let session_path = base_path.join("session_data.json");
        let (session_uuid, response_count) = self.import_session_data(&participant_id, &session_path)
            .await
            .map_err(|e| ActivityError::ExecutionFailed(format!("Failed to import session: {}", e)))?;

        // Import emotion data
        let emotion_record_count = if !session_uuid.is_empty() {
            self.import_emotion_data(&participant_id, &base_path, &session_uuid)
                .await
                .unwrap_or(0)
        } else {
            0
        };

        let outputs = vec![
            ActivityData {
                id: "import_result".to_string(),
                r#type: "https://spirit-in-physics.gftd.ai/ontology#ImportResult".to_string(),
                data: json!({
                    "participant_id": participant_id,
                    "success": true,
                    "session_events": response_count,
                    "emotion_records": emotion_record_count,
                    "session_uuid": session_uuid,
                }),
            },
        ];

        context.outputs = outputs.clone();

        let execution_time = start_time.elapsed().as_millis() as u64;

        Ok(ActivityExecutionResult {
            activity_id: self.id().to_string(),
            success: true,
            outputs,
            error: None,
            execution_time_ms: execution_time,
            timestamp: Utc::now(),
        })
    }

    fn validate_inputs(&self, inputs: &[ActivityData]) -> ActivityResult<()> {
        let has_participant_id = inputs.iter()
            .any(|input| input.r#type == "https://spirit-in-physics.gftd.ai/ontology#ParticipantId");

        if !has_participant_id {
            return Err(ActivityError::InvalidInput(
                "Participant ID is required".to_string()
            ));
        }

        Ok(())
    }

    fn check_conditions(&self, context: &ActivityContext) -> ActivityResult<()> {
        // Dataset directory must exist and be readable
        // This is checked in execute() method
        self.validate_inputs(&context.inputs)
    }

    fn apply_rules(&self, _context: &mut ActivityContext) -> ActivityResult<()> {
        // All IDs must be generated by the database
        // This is enforced in execute() method (no manual ID generation)
        Ok(())
    }
}

impl Default for DataImportActivity {
    fn default() -> Self {
        Self::new()
    }
}

