apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/gcp

patches:
  - target:
      kind: Gateway
      name: infra-gateway
    patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: infra-gateway
        annotations:
          networking.gke.io/static-ip: sip-static-ip
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
