apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grpc-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grpc-service
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@infra-timescaledb:5432/spirit_in_physics
        - name: TEMPORAL_ADDRESS
          value: infra-temporal:7233
        - name: STORAGE_ENDPOINT
          value: storage.googleapis.com
        - name: STORAGE_BUCKET
          value: spirit-in-physics
        - name: STORAGE_USE_SSL
          value: "true"
        image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/grpc-service:latest
        name: grpc-service
        ports:
        - containerPort: 8080
          name: http
