apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-service
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: import-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: import-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "import-service"
        dapr.io/app-port: "8082"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@infra-timescaledb:5432/spirit_in_physics
        - name: TEMPORAL_ADDRESS
          value: infra-temporal:7233
        image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/import-service:latest
        name: import-service
        ports:
        - containerPort: 8082
          name: http
