apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: infra
    app.kubernetes.io/version: 0.0.0-devel
  name: infra-temporal
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
      app.kubernetes.io/name: infra
  template:
    metadata:
      labels:
        app: temporal
        app.kubernetes.io/name: infra
    spec:
      containers:
      - env:
        - name: DB
          value: postgres12
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PWD
          value: postgres
        - name: POSTGRES_SEEDS
          value: infra-timescaledb
        - name: SKIP_DB_CREATE
          value: "false"
        - name: BIND_ON_IP
          value: 0.0.0.0
        image: temporalio/auto-setup:latest
        name: temporal
        ports:
        - containerPort: 7233
          name: grpc
        - containerPort: 8088
          name: ui
        resources:
          requests:
            cpu: 250m
            memory: 512Mi

