apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-temporal
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
      - env:
        - name: DB
          value: postgres12
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PWD
          value: postgres
        - name: POSTGRES_SEEDS
          value: infra-timescaledb
        image: temporalio/auto-setup:latest
        name: temporal
        ports:
        - containerPort: 7233
          name: grpc
        - containerPort: 8088
          name: ui
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
