apiVersion: apps/v1
kind: Deployment
metadata:
  name: researcher
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: researcher
  template:
    metadata:
      labels:
        app: researcher
    spec:
      containers:
      - name: researcher
        image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/researcher:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
