apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ts
  namespace: spirit-in-physics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal-ts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temporal-ts
    spec:
      containers:
      - env:
        - name: TEMPORAL_ADDRESS
          value: infra-temporal:7233
        - name: TASK_QUEUE
          value: visualization-analysis-queue
        image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/temporal-ts:latest
        name: temporal-ts
        ports:
        - containerPort: 3000
          name: http
