apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sip-tls-cert
  namespace: spirit-in-physics
spec:
  commonName: spirit-in-physics.com
  dnsNames:
  - spirit-in-physics.com
  - sip.junkawasaki.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: sip-tls-cert
