apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sip-tls-cert
  namespace: spirit-in-physics
spec:
  commonName: sip.junkawasaki.com
  dnsNames:
  - sip.junkawasaki.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: sip-tls-cert

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: junkawasaki@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: infra-gateway
            namespace: spirit-in-physics

