# GraphQL Mutations for Researcher Actor

mutation CalculateEmotionDistance($input: CalculateEmotionDistanceInput!) {
  calculateEmotionDistance(input: $input) {
    nodes {
      id
      label
      x
      y
      z
      color
      size
      metadata {
        word
        reactionTime
        emotionScore
        observationRatio
      }
    }
    edges {
      source
      target
      weight
      distance
      color
      width
    }
    metadata {
      totalNodes
      totalEdges
      method
      dimensions
      averageDistance
      clusteringCoefficient
    }
  }
}

