apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: oci
  oci:
    image: asia-northeast1-docker.pkg.dev/com-junkawasaki-sip/spirit-in-physics/manifests:latest
    auth: gcpserviceaccount
    gcpServiceAccountEmail: config-sync-sa@com-junkawasaki-sip.iam.gserviceaccount.com
