FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY dummy_main.go main.go
RUN go mod init dummy && go build -o grpc-service main.go
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/grpc-service .
EXPOSE 8080
CMD ["./grpc-service"]
