// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Participant struct {
	ID             pgtype.UUID        `json:"id"`
	Age            pgtype.Int4        `json:"age"`
	Gender         pgtype.Text        `json:"gender"`
	Handedness     pgtype.Text        `json:"handedness"`
	AgeGroup       pgtype.Text        `json:"age_group"`
	Ethnicity      pgtype.Text        `json:"ethnicity"`
	IncomeRange    pgtype.Text        `json:"income_range"`
	MedicalHistory []string           `json:"medical_history"`
	IsPublic       pgtype.Bool        `json:"is_public"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PhysiologicalMeasurement struct {
	ID                         pgtype.UUID        `json:"id"`
	TimelinePointTime          pgtype.Timestamptz `json:"timeline_point_time"`
	TimelinePointParticipantID pgtype.UUID        `json:"timeline_point_participant_id"`
	TimelinePointSessionID     pgtype.UUID        `json:"timeline_point_session_id"`
	MeasurementType            string             `json:"measurement_type"`
	Value                      float64            `json:"value"`
	Unit                       pgtype.Text        `json:"unit"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID            pgtype.UUID        `json:"id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	SessionIndex  pgtype.Int4        `json:"session_index"`
	StartTs       int64              `json:"start_ts"`
	EndTs         pgtype.Int8        `json:"end_ts"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SessionEvent struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	EventType      string             `json:"event_type"`
	EventTimestamp int64              `json:"event_timestamp"`
	EventData      []byte             `json:"event_data"`
	WordID         pgtype.Int4        `json:"word_id"`
	ReactionTimeMs pgtype.Int4        `json:"reaction_time_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StimulusWord struct {
	ID            int32              `json:"id"`
	Japanese      string             `json:"japanese"`
	English       string             `json:"english"`
	Pronunciation string             `json:"pronunciation"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TimelineEmotionEntry struct {
	ID                         pgtype.UUID        `json:"id"`
	TimelinePointTime          pgtype.Timestamptz `json:"timeline_point_time"`
	TimelinePointParticipantID pgtype.UUID        `json:"timeline_point_participant_id"`
	TimelinePointSessionID     pgtype.UUID        `json:"timeline_point_session_id"`
	EmotionName                string             `json:"emotion_name"`
	Score                      float64            `json:"score"`
	FileType                   string             `json:"file_type"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type TimelineEmotionVectorsByWord struct {
	ParticipantID     pgtype.UUID `json:"participant_id"`
	SessionID         pgtype.UUID `json:"session_id"`
	Word              pgtype.Text `json:"word"`
	JoySum            float64     `json:"joy_sum"`
	SadnessSum        float64     `json:"sadness_sum"`
	AngerSum          float64     `json:"anger_sum"`
	FearSum           float64     `json:"fear_sum"`
	SurpriseSum       float64     `json:"surprise_sum"`
	DisgustSum        float64     `json:"disgust_sum"`
	CalmSum           float64     `json:"calm_sum"`
	FocusSum          float64     `json:"focus_sum"`
	ExcitementSum     float64     `json:"excitement_sum"`
	ConfusionSum      float64     `json:"confusion_sum"`
	EmotionEntryCount int64       `json:"emotion_entry_count"`
	EmotionByModality interface{} `json:"emotion_by_modality"`
}

type TimelinePoint struct {
	Time          pgtype.Timestamptz `json:"time"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	Word          pgtype.Text        `json:"word"`
	EventType     pgtype.Text        `json:"event_type"`
	ReactionValue pgtype.Float8      `json:"reaction_value"`
	ReactionTime  pgtype.Float8      `json:"reaction_time"`
	HasResponse   pgtype.Bool        `json:"has_response"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TimelineWordAggregatesBySession struct {
	ParticipantID    pgtype.UUID `json:"participant_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	Word             pgtype.Text `json:"word"`
	Count            int64       `json:"count"`
	AvgReactionValue float64     `json:"avg_reaction_value"`
	SumReactionValue float64     `json:"sum_reaction_value"`
	AvgReactionTime  float64     `json:"avg_reaction_time"`
	SumReactionTime  float64     `json:"sum_reaction_time"`
	AvgPhysiological float64     `json:"avg_physiological"`
	SumPhysAbs       float64     `json:"sum_phys_abs"`
	PhysSeries       interface{} `json:"phys_series"`
	RtSeries         interface{} `json:"rt_series"`
	RvSeries         interface{} `json:"rv_series"`
	FirstTime        interface{} `json:"first_time"`
	LastTime         interface{} `json:"last_time"`
}

type TimelineWordStatisticsBySession struct {
	ParticipantID    pgtype.UUID `json:"participant_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	Word             pgtype.Text `json:"word"`
	Count            int64       `json:"count"`
	AvgReactionTime  float64     `json:"avg_reaction_time"`
	StdReactionTime  float64     `json:"std_reaction_time"`
	VarReactionTime  float64     `json:"var_reaction_time"`
	AvgReactionValue float64     `json:"avg_reaction_value"`
	StdReactionValue float64     `json:"std_reaction_value"`
	VarReactionValue float64     `json:"var_reaction_value"`
	AvgPhysiological float64     `json:"avg_physiological"`
	StdPhysiological float64     `json:"std_physiological"`
	VarPhysiological float64     `json:"var_physiological"`
	SpeedIndex       float64     `json:"speed_index"`
	PhysSeries       interface{} `json:"phys_series"`
	RtSeries         interface{} `json:"rt_series"`
}
