// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (
    id, age_group, ethnicity, income_range, medical_history, is_public, created_at, updated_at
)
VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    COALESCE($6::boolean, true), 
    $7, 
    $8
)
ON CONFLICT (id) DO UPDATE SET 
    age_group = EXCLUDED.age_group,
    ethnicity = EXCLUDED.ethnicity,
    income_range = EXCLUDED.income_range,
    medical_history = EXCLUDED.medical_history,
    updated_at = EXCLUDED.updated_at
RETURNING id, age, gender, handedness, age_group, ethnicity, income_range, medical_history, is_public, created_at, updated_at
`

type CreateParticipantParams struct {
	ID             pgtype.UUID        `json:"id"`
	AgeGroup       pgtype.Text        `json:"age_group"`
	Ethnicity      pgtype.Text        `json:"ethnicity"`
	IncomeRange    pgtype.Text        `json:"income_range"`
	MedicalHistory []string           `json:"medical_history"`
	IsPublic       pgtype.Bool        `json:"is_public"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.ID,
		arg.AgeGroup,
		arg.Ethnicity,
		arg.IncomeRange,
		arg.MedicalHistory,
		arg.IsPublic,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Age,
		&i.Gender,
		&i.Handedness,
		&i.AgeGroup,
		&i.Ethnicity,
		&i.IncomeRange,
		&i.MedicalHistory,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, age, gender, handedness, age_group, ethnicity, income_range, medical_history, is_public, created_at, updated_at
FROM participants
WHERE id = $1
`

func (q *Queries) GetParticipant(ctx context.Context, id pgtype.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Age,
		&i.Gender,
		&i.Handedness,
		&i.AgeGroup,
		&i.Ethnicity,
		&i.IncomeRange,
		&i.MedicalHistory,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipants = `-- name: GetParticipants :many
SELECT id, age, gender, handedness, age_group, ethnicity, income_range, medical_history, is_public, created_at, updated_at
FROM participants
WHERE ($1::boolean IS NULL OR is_public = $1)
ORDER BY created_at DESC
`

func (q *Queries) GetParticipants(ctx context.Context, dollar_1 bool) ([]Participant, error) {
	rows, err := q.db.Query(ctx, getParticipants, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.Age,
			&i.Gender,
			&i.Handedness,
			&i.AgeGroup,
			&i.Ethnicity,
			&i.IncomeRange,
			&i.MedicalHistory,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStimulusWord = `-- name: GetStimulusWord :one
SELECT id, japanese, english, pronunciation
FROM stimulus_words
WHERE id = $1
`

type GetStimulusWordRow struct {
	ID            int32  `json:"id"`
	Japanese      string `json:"japanese"`
	English       string `json:"english"`
	Pronunciation string `json:"pronunciation"`
}

func (q *Queries) GetStimulusWord(ctx context.Context, id int32) (GetStimulusWordRow, error) {
	row := q.db.QueryRow(ctx, getStimulusWord, id)
	var i GetStimulusWordRow
	err := row.Scan(
		&i.ID,
		&i.Japanese,
		&i.English,
		&i.Pronunciation,
	)
	return i, err
}

const getStimulusWords = `-- name: GetStimulusWords :many
SELECT id, japanese, english, pronunciation
FROM stimulus_words
ORDER BY id
`

type GetStimulusWordsRow struct {
	ID            int32  `json:"id"`
	Japanese      string `json:"japanese"`
	English       string `json:"english"`
	Pronunciation string `json:"pronunciation"`
}

func (q *Queries) GetStimulusWords(ctx context.Context) ([]GetStimulusWordsRow, error) {
	rows, err := q.db.Query(ctx, getStimulusWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStimulusWordsRow{}
	for rows.Next() {
		var i GetStimulusWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Japanese,
			&i.English,
			&i.Pronunciation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
