// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error)
	CreatePhysiologicalMeasurement(ctx context.Context, arg CreatePhysiologicalMeasurementParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionEvent(ctx context.Context, arg CreateSessionEventParams) error
	CreateTimelineEmotionEntry(ctx context.Context, arg CreateTimelineEmotionEntryParams) error
	CreateTimelinePoint(ctx context.Context, arg CreateTimelinePointParams) error
	GetEmotionVectors(ctx context.Context, arg GetEmotionVectorsParams) ([]GetEmotionVectorsRow, error)
	GetParticipant(ctx context.Context, id pgtype.UUID) (Participant, error)
	GetParticipantByEmail(ctx context.Context, email pgtype.Text) (Participant, error)
	GetParticipants(ctx context.Context, dollar_1 bool) ([]Participant, error)
	GetSessions(ctx context.Context, participantID pgtype.UUID) ([]GetSessionsRow, error)
	GetSessionsWithPublicCheck(ctx context.Context, participantID pgtype.UUID) ([]GetSessionsWithPublicCheckRow, error)
	GetStimulusWord(ctx context.Context, id int32) (GetStimulusWordRow, error)
	GetStimulusWords(ctx context.Context) ([]GetStimulusWordsRow, error)
	GetTimelinePoints(ctx context.Context, arg GetTimelinePointsParams) ([]GetTimelinePointsRow, error)
	GetTimelinePointsWithPublicCheck(ctx context.Context, arg GetTimelinePointsWithPublicCheckParams) ([]GetTimelinePointsWithPublicCheckRow, error)
	GetWordAggregates(ctx context.Context, arg GetWordAggregatesParams) ([]GetWordAggregatesRow, error)
	GetWordStatistics(ctx context.Context, arg GetWordStatisticsParams) ([]GetWordStatisticsRow, error)
	UpsertStimulusWord(ctx context.Context, arg UpsertStimulusWordParams) error
}

var _ Querier = (*Queries)(nil)
