// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, participant_id, session_index, start_ts, end_ts, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, participant_id, session_index, start_ts, end_ts, created_at, updated_at
`

type CreateSessionParams struct {
	ID            pgtype.UUID        `json:"id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	SessionIndex  pgtype.Int4        `json:"session_index"`
	StartTs       int64              `json:"start_ts"`
	EndTs         pgtype.Int8        `json:"end_ts"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ParticipantID,
		arg.SessionIndex,
		arg.StartTs,
		arg.EndTs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.SessionIndex,
		&i.StartTs,
		&i.EndTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionEvent = `-- name: CreateSessionEvent :exec
INSERT INTO session_events (session_id, event_type, event_timestamp, event_data, word_id, reaction_time_ms)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type CreateSessionEventParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	EventType      string      `json:"event_type"`
	EventTimestamp int64       `json:"event_timestamp"`
	EventData      []byte      `json:"event_data"`
	WordID         pgtype.Int4 `json:"word_id"`
	ReactionTimeMs pgtype.Int4 `json:"reaction_time_ms"`
}

func (q *Queries) CreateSessionEvent(ctx context.Context, arg CreateSessionEventParams) error {
	_, err := q.db.Exec(ctx, createSessionEvent,
		arg.SessionID,
		arg.EventType,
		arg.EventTimestamp,
		arg.EventData,
		arg.WordID,
		arg.ReactionTimeMs,
	)
	return err
}

const getSessions = `-- name: GetSessions :many
SELECT 
    s.id,
    s.participant_id,
    s.session_index,
    s.start_ts,
    s.end_ts,
    s.created_at,
    s.updated_at,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'type', se.event_type::text,
                'timestamp', se.event_timestamp,
                'data', se.event_data,
                'word_id', se.word_id,
                'reaction_time_ms', se.reaction_time_ms
            )
        ) FILTER (WHERE se.id IS NOT NULL),
        '[]'::json
    ) as events
FROM sessions s
LEFT JOIN session_events se ON se.session_id = s.id
WHERE s.participant_id = $1
GROUP BY s.id, s.participant_id, s.session_index, s.start_ts, s.end_ts, s.created_at, s.updated_at
ORDER BY s.session_index ASC
`

type GetSessionsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	SessionIndex  pgtype.Int4        `json:"session_index"`
	StartTs       int64              `json:"start_ts"`
	EndTs         pgtype.Int8        `json:"end_ts"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Events        interface{}        `json:"events"`
}

func (q *Queries) GetSessions(ctx context.Context, participantID pgtype.UUID) ([]GetSessionsRow, error) {
	rows, err := q.db.Query(ctx, getSessions, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionsRow{}
	for rows.Next() {
		var i GetSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.SessionIndex,
			&i.StartTs,
			&i.EndTs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsWithPublicCheck = `-- name: GetSessionsWithPublicCheck :many
SELECT 
    s.id,
    s.participant_id,
    s.session_index,
    s.start_ts,
    s.end_ts,
    s.created_at,
    s.updated_at,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'type', se.event_type::text,
                'timestamp', se.event_timestamp,
                'data', se.event_data,
                'word_id', se.word_id,
                'reaction_time_ms', se.reaction_time_ms
            )
        ) FILTER (WHERE se.id IS NOT NULL),
        '[]'::json
    ) as events
FROM sessions s
INNER JOIN participants p ON p.id = s.participant_id
LEFT JOIN session_events se ON se.session_id = s.id
WHERE s.participant_id = $1 AND p.is_public = true
GROUP BY s.id, s.participant_id, s.session_index, s.start_ts, s.end_ts, s.created_at, s.updated_at
ORDER BY s.session_index ASC
`

type GetSessionsWithPublicCheckRow struct {
	ID            pgtype.UUID        `json:"id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	SessionIndex  pgtype.Int4        `json:"session_index"`
	StartTs       int64              `json:"start_ts"`
	EndTs         pgtype.Int8        `json:"end_ts"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Events        interface{}        `json:"events"`
}

func (q *Queries) GetSessionsWithPublicCheck(ctx context.Context, participantID pgtype.UUID) ([]GetSessionsWithPublicCheckRow, error) {
	rows, err := q.db.Query(ctx, getSessionsWithPublicCheck, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionsWithPublicCheckRow{}
	for rows.Next() {
		var i GetSessionsWithPublicCheckRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.SessionIndex,
			&i.StartTs,
			&i.EndTs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
