// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeline.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhysiologicalMeasurement = `-- name: CreatePhysiologicalMeasurement :exec
INSERT INTO physiological_measurements (timeline_point_time, timeline_point_participant_id, timeline_point_session_id, measurement_type, value, unit)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePhysiologicalMeasurementParams struct {
	TimelinePointTime          pgtype.Timestamptz `json:"timeline_point_time"`
	TimelinePointParticipantID string             `json:"timeline_point_participant_id"`
	TimelinePointSessionID     pgtype.UUID        `json:"timeline_point_session_id"`
	MeasurementType            string             `json:"measurement_type"`
	Value                      float64            `json:"value"`
	Unit                       pgtype.Text        `json:"unit"`
}

func (q *Queries) CreatePhysiologicalMeasurement(ctx context.Context, arg CreatePhysiologicalMeasurementParams) error {
	_, err := q.db.Exec(ctx, createPhysiologicalMeasurement,
		arg.TimelinePointTime,
		arg.TimelinePointParticipantID,
		arg.TimelinePointSessionID,
		arg.MeasurementType,
		arg.Value,
		arg.Unit,
	)
	return err
}

const createTimelineEmotionEntry = `-- name: CreateTimelineEmotionEntry :exec
INSERT INTO timeline_emotion_entries (timeline_point_time, timeline_point_participant_id, timeline_point_session_id, emotion_name, score, file_type)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTimelineEmotionEntryParams struct {
	TimelinePointTime          pgtype.Timestamptz `json:"timeline_point_time"`
	TimelinePointParticipantID string             `json:"timeline_point_participant_id"`
	TimelinePointSessionID     pgtype.UUID        `json:"timeline_point_session_id"`
	EmotionName                string             `json:"emotion_name"`
	Score                      float64            `json:"score"`
	FileType                   string             `json:"file_type"`
}

func (q *Queries) CreateTimelineEmotionEntry(ctx context.Context, arg CreateTimelineEmotionEntryParams) error {
	_, err := q.db.Exec(ctx, createTimelineEmotionEntry,
		arg.TimelinePointTime,
		arg.TimelinePointParticipantID,
		arg.TimelinePointSessionID,
		arg.EmotionName,
		arg.Score,
		arg.FileType,
	)
	return err
}

const createTimelinePoint = `-- name: CreateTimelinePoint :exec
INSERT INTO timeline_points (time, participant_id, session_id, word, event_type, reaction_value, reaction_time, has_response)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (time, participant_id, session_id) DO NOTHING
`

type CreateTimelinePointParams struct {
	Time          pgtype.Timestamptz `json:"time"`
	ParticipantID string             `json:"participant_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	Word          pgtype.Text        `json:"word"`
	EventType     pgtype.Text        `json:"event_type"`
	ReactionValue pgtype.Float8      `json:"reaction_value"`
	ReactionTime  pgtype.Float8      `json:"reaction_time"`
	HasResponse   pgtype.Bool        `json:"has_response"`
}

func (q *Queries) CreateTimelinePoint(ctx context.Context, arg CreateTimelinePointParams) error {
	_, err := q.db.Exec(ctx, createTimelinePoint,
		arg.Time,
		arg.ParticipantID,
		arg.SessionID,
		arg.Word,
		arg.EventType,
		arg.ReactionValue,
		arg.ReactionTime,
		arg.HasResponse,
	)
	return err
}

const getEmotionVectors = `-- name: GetEmotionVectors :many
SELECT 
    participant_id,
    session_id,
    word,
    joy_sum::float8 as joy_sum,
    sadness_sum::float8 as sadness_sum,
    anger_sum::float8 as anger_sum,
    fear_sum::float8 as fear_sum,
    surprise_sum::float8 as surprise_sum,
    disgust_sum::float8 as disgust_sum,
    calm_sum::float8 as calm_sum,
    focus_sum::float8 as focus_sum,
    excitement_sum::float8 as excitement_sum,
    confusion_sum::float8 as confusion_sum,
    emotion_entry_count,
    emotion_by_modality
FROM timeline_emotion_vectors_by_word
WHERE participant_id = $1
    AND ($2::uuid IS NULL OR session_id = $2)
ORDER BY word ASC
`

type GetEmotionVectorsParams struct {
	ParticipantID string      `json:"participant_id"`
	Column2       pgtype.UUID `json:"column_2"`
}

type GetEmotionVectorsRow struct {
	ParticipantID     string      `json:"participant_id"`
	SessionID         pgtype.UUID `json:"session_id"`
	Word              pgtype.Text `json:"word"`
	JoySum            float64     `json:"joy_sum"`
	SadnessSum        float64     `json:"sadness_sum"`
	AngerSum          float64     `json:"anger_sum"`
	FearSum           float64     `json:"fear_sum"`
	SurpriseSum       float64     `json:"surprise_sum"`
	DisgustSum        float64     `json:"disgust_sum"`
	CalmSum           float64     `json:"calm_sum"`
	FocusSum          float64     `json:"focus_sum"`
	ExcitementSum     float64     `json:"excitement_sum"`
	ConfusionSum      float64     `json:"confusion_sum"`
	EmotionEntryCount int64       `json:"emotion_entry_count"`
	EmotionByModality interface{} `json:"emotion_by_modality"`
}

func (q *Queries) GetEmotionVectors(ctx context.Context, arg GetEmotionVectorsParams) ([]GetEmotionVectorsRow, error) {
	rows, err := q.db.Query(ctx, getEmotionVectors, arg.ParticipantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmotionVectorsRow{}
	for rows.Next() {
		var i GetEmotionVectorsRow
		if err := rows.Scan(
			&i.ParticipantID,
			&i.SessionID,
			&i.Word,
			&i.JoySum,
			&i.SadnessSum,
			&i.AngerSum,
			&i.FearSum,
			&i.SurpriseSum,
			&i.DisgustSum,
			&i.CalmSum,
			&i.FocusSum,
			&i.ExcitementSum,
			&i.ConfusionSum,
			&i.EmotionEntryCount,
			&i.EmotionByModality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimelinePoints = `-- name: GetTimelinePoints :many
SELECT 
    tp.time,
    tp.participant_id,
    tp.session_id,
    tp.word,
    tp.event_type,
    tp.reaction_value,
    tp.reaction_time,
    tp.has_response,
    COALESCE(
        json_agg(
            DISTINCT jsonb_build_object(
                'name', tee.emotion_name::text,
                'score', tee.score,
                'file_type', tee.file_type::text
            )
        ) FILTER (WHERE tee.id IS NOT NULL),
        '[]'::json
    ) as emotions,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'measurement_type', pm.measurement_type::text,
                'value', pm.value,
                'unit', COALESCE(pm.unit::text, 'unknown'),
                'timestamp', tp.time::text
            )
        ) FILTER (WHERE pm.id IS NOT NULL),
        '[]'::json
    ) as physiological
FROM timeline_points tp
LEFT JOIN timeline_emotion_entries tee ON 
    tee.timeline_point_time = tp.time AND
    tee.timeline_point_participant_id = tp.participant_id AND
    tee.timeline_point_session_id = tp.session_id
LEFT JOIN physiological_measurements pm ON
    pm.timeline_point_time = tp.time AND
    pm.timeline_point_participant_id = tp.participant_id AND
    pm.timeline_point_session_id = tp.session_id
WHERE tp.participant_id = $1
    AND ($2::uuid IS NULL OR tp.session_id = $2)
    AND ($3::timestamptz IS NULL OR tp.time >= $3)
    AND ($4::timestamptz IS NULL OR tp.time <= $4)
GROUP BY tp.time, tp.participant_id, tp.session_id, tp.word, tp.event_type, tp.reaction_value, tp.reaction_time, tp.has_response
ORDER BY tp.time ASC
LIMIT 20000
`

type GetTimelinePointsParams struct {
	ParticipantID string             `json:"participant_id"`
	Column2       pgtype.UUID        `json:"column_2"`
	Column3       pgtype.Timestamptz `json:"column_3"`
	Column4       pgtype.Timestamptz `json:"column_4"`
}

type GetTimelinePointsRow struct {
	Time          pgtype.Timestamptz `json:"time"`
	ParticipantID string             `json:"participant_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	Word          pgtype.Text        `json:"word"`
	EventType     pgtype.Text        `json:"event_type"`
	ReactionValue pgtype.Float8      `json:"reaction_value"`
	ReactionTime  pgtype.Float8      `json:"reaction_time"`
	HasResponse   pgtype.Bool        `json:"has_response"`
	Emotions      interface{}        `json:"emotions"`
	Physiological interface{}        `json:"physiological"`
}

func (q *Queries) GetTimelinePoints(ctx context.Context, arg GetTimelinePointsParams) ([]GetTimelinePointsRow, error) {
	rows, err := q.db.Query(ctx, getTimelinePoints,
		arg.ParticipantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimelinePointsRow{}
	for rows.Next() {
		var i GetTimelinePointsRow
		if err := rows.Scan(
			&i.Time,
			&i.ParticipantID,
			&i.SessionID,
			&i.Word,
			&i.EventType,
			&i.ReactionValue,
			&i.ReactionTime,
			&i.HasResponse,
			&i.Emotions,
			&i.Physiological,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimelinePointsWithPublicCheck = `-- name: GetTimelinePointsWithPublicCheck :many
SELECT 
    tp.time,
    tp.participant_id,
    tp.session_id,
    tp.word,
    tp.event_type,
    tp.reaction_value,
    tp.reaction_time,
    tp.has_response,
    COALESCE(
        json_agg(
            DISTINCT jsonb_build_object(
                'name', tee.emotion_name::text,
                'score', tee.score,
                'file_type', tee.file_type::text
            )
        ) FILTER (WHERE tee.id IS NOT NULL),
        '[]'::json
    ) as emotions,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'measurement_type', pm.measurement_type::text,
                'value', pm.value,
                'unit', COALESCE(pm.unit::text, 'unknown'),
                'timestamp', tp.time::text
            )
        ) FILTER (WHERE pm.id IS NOT NULL),
        '[]'::json
    ) as physiological
FROM timeline_points tp
INNER JOIN participants p ON p.id = tp.participant_id
LEFT JOIN timeline_emotion_entries tee ON 
    tee.timeline_point_time = tp.time AND
    tee.timeline_point_participant_id = tp.participant_id AND
    tee.timeline_point_session_id = tp.session_id
LEFT JOIN physiological_measurements pm ON
    pm.timeline_point_time = tp.time AND
    pm.timeline_point_participant_id = tp.participant_id AND
    pm.timeline_point_session_id = tp.session_id
WHERE tp.participant_id = $1 AND p.is_public = true
    AND ($2::uuid IS NULL OR tp.session_id = $2)
    AND ($3::timestamptz IS NULL OR tp.time >= $3)
    AND ($4::timestamptz IS NULL OR tp.time <= $4)
GROUP BY tp.time, tp.participant_id, tp.session_id, tp.word, tp.event_type, tp.reaction_value, tp.reaction_time, tp.has_response
ORDER BY tp.time ASC
LIMIT 20000
`

type GetTimelinePointsWithPublicCheckParams struct {
	ParticipantID string             `json:"participant_id"`
	Column2       pgtype.UUID        `json:"column_2"`
	Column3       pgtype.Timestamptz `json:"column_3"`
	Column4       pgtype.Timestamptz `json:"column_4"`
}

type GetTimelinePointsWithPublicCheckRow struct {
	Time          pgtype.Timestamptz `json:"time"`
	ParticipantID string             `json:"participant_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	Word          pgtype.Text        `json:"word"`
	EventType     pgtype.Text        `json:"event_type"`
	ReactionValue pgtype.Float8      `json:"reaction_value"`
	ReactionTime  pgtype.Float8      `json:"reaction_time"`
	HasResponse   pgtype.Bool        `json:"has_response"`
	Emotions      interface{}        `json:"emotions"`
	Physiological interface{}        `json:"physiological"`
}

func (q *Queries) GetTimelinePointsWithPublicCheck(ctx context.Context, arg GetTimelinePointsWithPublicCheckParams) ([]GetTimelinePointsWithPublicCheckRow, error) {
	rows, err := q.db.Query(ctx, getTimelinePointsWithPublicCheck,
		arg.ParticipantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimelinePointsWithPublicCheckRow{}
	for rows.Next() {
		var i GetTimelinePointsWithPublicCheckRow
		if err := rows.Scan(
			&i.Time,
			&i.ParticipantID,
			&i.SessionID,
			&i.Word,
			&i.EventType,
			&i.ReactionValue,
			&i.ReactionTime,
			&i.HasResponse,
			&i.Emotions,
			&i.Physiological,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWordAggregates = `-- name: GetWordAggregates :many
SELECT 
    participant_id,
    session_id,
    word,
    count,
    avg_reaction_value::float8 as avg_reaction_value,
    sum_reaction_value::float8 as sum_reaction_value,
    avg_reaction_time::float8 as avg_reaction_time,
    sum_reaction_time::float8 as sum_reaction_time,
    avg_physiological::float8 as avg_physiological,
    sum_phys_abs::float8 as sum_phys_abs,
    phys_series,
    rt_series,
    rv_series,
    first_time,
    last_time
FROM timeline_word_aggregates_by_session
WHERE participant_id = $1
    AND ($2::uuid IS NULL OR session_id = $2)
ORDER BY word ASC
`

type GetWordAggregatesParams struct {
	ParticipantID string      `json:"participant_id"`
	Column2       pgtype.UUID `json:"column_2"`
}

type GetWordAggregatesRow struct {
	ParticipantID    string      `json:"participant_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	Word             pgtype.Text `json:"word"`
	Count            int64       `json:"count"`
	AvgReactionValue float64     `json:"avg_reaction_value"`
	SumReactionValue float64     `json:"sum_reaction_value"`
	AvgReactionTime  float64     `json:"avg_reaction_time"`
	SumReactionTime  float64     `json:"sum_reaction_time"`
	AvgPhysiological float64     `json:"avg_physiological"`
	SumPhysAbs       float64     `json:"sum_phys_abs"`
	PhysSeries       interface{} `json:"phys_series"`
	RtSeries         interface{} `json:"rt_series"`
	RvSeries         interface{} `json:"rv_series"`
	FirstTime        interface{} `json:"first_time"`
	LastTime         interface{} `json:"last_time"`
}

func (q *Queries) GetWordAggregates(ctx context.Context, arg GetWordAggregatesParams) ([]GetWordAggregatesRow, error) {
	rows, err := q.db.Query(ctx, getWordAggregates, arg.ParticipantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWordAggregatesRow{}
	for rows.Next() {
		var i GetWordAggregatesRow
		if err := rows.Scan(
			&i.ParticipantID,
			&i.SessionID,
			&i.Word,
			&i.Count,
			&i.AvgReactionValue,
			&i.SumReactionValue,
			&i.AvgReactionTime,
			&i.SumReactionTime,
			&i.AvgPhysiological,
			&i.SumPhysAbs,
			&i.PhysSeries,
			&i.RtSeries,
			&i.RvSeries,
			&i.FirstTime,
			&i.LastTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWordStatistics = `-- name: GetWordStatistics :many
SELECT 
    participant_id,
    session_id,
    word,
    count,
    avg_reaction_time::float8 as avg_reaction_time,
    std_reaction_time::float8 as std_reaction_time,
    var_reaction_time::float8 as var_reaction_time,
    avg_reaction_value::float8 as avg_reaction_value,
    std_reaction_value::float8 as std_reaction_value,
    var_reaction_value::float8 as var_reaction_value,
    avg_physiological::float8 as avg_physiological,
    std_physiological::float8 as std_physiological,
    var_physiological::float8 as var_physiological,
    speed_index::float8 as speed_index,
    phys_series,
    rt_series
FROM timeline_word_statistics_by_session
WHERE participant_id = $1
    AND ($2::uuid IS NULL OR session_id = $2)
ORDER BY word ASC
`

type GetWordStatisticsParams struct {
	ParticipantID string      `json:"participant_id"`
	Column2       pgtype.UUID `json:"column_2"`
}

type GetWordStatisticsRow struct {
	ParticipantID    string      `json:"participant_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	Word             pgtype.Text `json:"word"`
	Count            int64       `json:"count"`
	AvgReactionTime  float64     `json:"avg_reaction_time"`
	StdReactionTime  float64     `json:"std_reaction_time"`
	VarReactionTime  float64     `json:"var_reaction_time"`
	AvgReactionValue float64     `json:"avg_reaction_value"`
	StdReactionValue float64     `json:"std_reaction_value"`
	VarReactionValue float64     `json:"var_reaction_value"`
	AvgPhysiological float64     `json:"avg_physiological"`
	StdPhysiological float64     `json:"std_physiological"`
	VarPhysiological float64     `json:"var_physiological"`
	SpeedIndex       float64     `json:"speed_index"`
	PhysSeries       interface{} `json:"phys_series"`
	RtSeries         interface{} `json:"rt_series"`
}

func (q *Queries) GetWordStatistics(ctx context.Context, arg GetWordStatisticsParams) ([]GetWordStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getWordStatistics, arg.ParticipantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWordStatisticsRow{}
	for rows.Next() {
		var i GetWordStatisticsRow
		if err := rows.Scan(
			&i.ParticipantID,
			&i.SessionID,
			&i.Word,
			&i.Count,
			&i.AvgReactionTime,
			&i.StdReactionTime,
			&i.VarReactionTime,
			&i.AvgReactionValue,
			&i.StdReactionValue,
			&i.VarReactionValue,
			&i.AvgPhysiological,
			&i.StdPhysiological,
			&i.VarPhysiological,
			&i.SpeedIndex,
			&i.PhysSeries,
			&i.RtSeries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
